### ISSUE TITLE
Brainstorming for Solo Traveler App

### ISSUE THREAD

**Issue by catpolk** [SSimonPhd/project3#2]
Slide presentation
Project approval 
Dividing job/responsibilities
Timeline 

Meeting on Monday Jan 16th at 6:30pm

**Comment by SSimonPhd** [comment]
Working on for Wednesday:
Web token & Authorization (S)
Chat and login (M & A)
Trip schema in db (C)
Database trip queries and mutations (C)
Home page once logged in (E)
CSS example based on mock up (E)
TO DO this week:
Database queries and mutation
Login functionality
Mutations & queries
Seed file for demo
Continue on chat feature
